spring:
  # ---------------------------------------------  数据库配置(默认使用mysql：5.5+) -----------------------------------#
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.23.20.109/test?characterEncoding=utf-8
    username: root
    password: 6789@jkl


  # --------------------------------------------- Mail配置 ------------------------------------------------------- #
  mail:
    port: 587
    host: smtp.qq.com
    username: 1064284972@qq,com
    password: gszlixebwzicbdhh

server:
  port: 8088
  servlet:
    context-path: /

sso:
  enable: true
#  url: http://172.23.27.231:8081
  url: http://www.sso.com:8081
# --------------------------------------------- 配置mybatis ---------------------------------------------------- #
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

